apiVersion: v1
kind: Secret
metadata:
  name: contract-postgres-secret
  namespace: freelance
type: Opaque
stringData:
  POSTGRES_USER: contractuser
  POSTGRES_PASSWORD: contractpass123
  POSTGRES_DB: freelancedb-contracts
