apiVersion: v1
kind: Secret
metadata:
  name: job-postgres-secret
  namespace: freelance
type: Opaque
stringData:
  POSTGRES_USER: jobuser
  POSTGRES_PASSWORD: jobpass123
  POSTGRES_DB: freelancedb-jobs

