apiVersion: v1
kind: Secret
metadata:
  name: proposal-postgres-secret
  namespace: freelance
type: Opaque
stringData:
  POSTGRES_USER: proposaluser
  POSTGRES_PASSWORD: proposalpass123
  POSTGRES_DB: freelancedb-proposals
