apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
  namespace: freelance
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://user-postgres:5432/freelancedb-users
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  SPRING_DATA_MONGODB_URI: mongodb://root:rootpass@mongo:27017/freelancemongo?authSource=admin
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: 6379
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
  SPRING_RABBITMQ_LISTENER_SIMPLE_ACKNOWLEDGE_MODE: auto
  SPRING_RABBITMQ_LISTENER_SIMPLE_DEFAULT_REQUEUE_REJECTED: "false"
  SPRING_RABBITMQ_LISTENER_SIMPLE_RETRY_ENABLED: "true"
  SPRING_RABBITMQ_LISTENER_SIMPLE_RETRY_MAX_ATTEMPTS: "3"
  JWT_EXPIRATION: "86400000"
  FEIGN_CONTRACT_SERVICE_URL: http://contract-service:8080
  FEIGN_WALLET_SERVICE_URL: http://wallet-service:8080
  LOKI_URL: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
